-- Moves the legacy "User" table into the userProfile / userPersonalDetails
-- structure, and reshapes the three user tables (originally created from the
-- ER-diagram SQL) to match prisma/schema.prisma.
--
-- Legacy field mapping:
--   User.name       -> fName / mName / lName  (split on whitespace)
--   User.email      -> userPersonalDetails.emailAddress, and the local-part
--                      becomes the profileName (login user id). If two users
--                      share a local-part, the full email is used instead.
--   User.passwordHash -> profilePassword  (bcrypt hashes carry over unchanged)
--   User.role       -> userType
--   User.createdAt  -> createDate
--   Attempt.userId  -> remapped from the cuid to the new integer id
--
-- Run once:  psql -d tasteurknowledge -f prisma/sql/001_migrate_user_to_user_profile.sql

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. UserType enum
-- ---------------------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE "UserType" AS ENUM ('STUDENT', 'PARENT', 'ADMIN');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ---------------------------------------------------------------------------
-- 2. Reshape userProfile to match the Prisma model
-- ---------------------------------------------------------------------------
ALTER TABLE "userProfile"
  ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
  ALTER COLUMN "fName"              TYPE TEXT,
  ALTER COLUMN "mName"              TYPE TEXT,
  ALTER COLUMN "lName"              TYPE TEXT,
  ALTER COLUMN "profileName"        TYPE TEXT,
  ALTER COLUMN "profilePassword"    TYPE TEXT,
  ALTER COLUMN "student_parent_ref" TYPE TEXT,
  ALTER COLUMN "createDate"         TYPE TIMESTAMP(3),
  ALTER COLUMN "createDate"         SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "isActive"           SET DEFAULT TRUE;

ALTER TABLE "userProfile"
  ALTER COLUMN "userType" TYPE "UserType"
    USING COALESCE(UPPER("userType"), 'STUDENT')::"UserType",
  ALTER COLUMN "userType" SET DEFAULT 'STUDENT';

-- Holds the old cuid while we remap Attempt; dropped at the end.
ALTER TABLE "userProfile" ADD COLUMN IF NOT EXISTS "legacy_id" TEXT;

-- ---------------------------------------------------------------------------
-- 3. Copy the legacy users across
-- ---------------------------------------------------------------------------
WITH parts AS (
  SELECT
    u.id,
    u.email,
    u."passwordHash",
    u.role,
    u."createdAt",
    string_to_array(regexp_replace(btrim(u.name), '\s+', ' ', 'g'), ' ') AS np
  FROM "User" u
),
named AS (
  SELECT
    p.*,
    p.np[1] AS f_name,
    CASE WHEN array_length(p.np, 1) > 1
         THEN p.np[array_length(p.np, 1)] END AS l_name,
    CASE WHEN array_length(p.np, 1) > 2
         THEN array_to_string(p.np[2:array_length(p.np, 1) - 1], ' ') END AS m_name,
    split_part(p.email, '@', 1) AS base_name
  FROM parts p
)
INSERT INTO "userProfile"
  ("fName", "mName", "lName", "profileName", "profilePassword",
   "userType", "isActive", "createDate", "legacy_id")
SELECT
  n.f_name,
  n.m_name,
  n.l_name,
  -- Fall back to the full email when the local-part is not unique
  CASE
    WHEN count(*) OVER (PARTITION BY n.base_name) > 1 THEN n.email
    WHEN EXISTS (SELECT 1 FROM "userProfile" e WHERE e."profileName" = n.base_name) THEN n.email
    ELSE n.base_name
  END,
  n."passwordHash",
  n.role::TEXT::"UserType",
  TRUE,
  n."createdAt",
  n.id
FROM named n;

-- ---------------------------------------------------------------------------
-- 4. Emails move into userPersonalDetails
-- ---------------------------------------------------------------------------
INSERT INTO "userPersonalDetails" ("userDetails_Id", "emailAddress")
SELECT p."id", u."email"
FROM "userProfile" p
JOIN "User" u ON u."id" = p."legacy_id";

-- ---------------------------------------------------------------------------
-- 5. Repoint Attempt.userId at the new integer key
-- ---------------------------------------------------------------------------
ALTER TABLE "Attempt" DROP CONSTRAINT IF EXISTS "Attempt_userId_fkey";
ALTER TABLE "Attempt" ADD COLUMN "userId_new" INTEGER;

UPDATE "Attempt" a
SET "userId_new" = p."id"
FROM "userProfile" p
WHERE p."legacy_id" = a."userId";

DO $$
DECLARE orphans INTEGER;
BEGIN
  SELECT count(*) INTO orphans FROM "Attempt" WHERE "userId_new" IS NULL;
  IF orphans > 0 THEN
    RAISE EXCEPTION '% attempt(s) could not be matched to a userProfile - aborting', orphans;
  END IF;
END $$;

ALTER TABLE "Attempt" DROP COLUMN "userId";
ALTER TABLE "Attempt" RENAME COLUMN "userId_new" TO "userId";
ALTER TABLE "Attempt" ALTER COLUMN "userId" SET NOT NULL;
ALTER TABLE "Attempt"
  ADD CONSTRAINT "Attempt_userId_fkey" FOREIGN KEY ("userId")
  REFERENCES "userProfile"("id") ON UPDATE CASCADE ON DELETE CASCADE;

-- ---------------------------------------------------------------------------
-- 6. Tighten userProfile now that the data is in
-- ---------------------------------------------------------------------------
ALTER TABLE "userProfile"
  ALTER COLUMN "profileName"     SET NOT NULL,
  ALTER COLUMN "profilePassword" SET NOT NULL,
  ALTER COLUMN "userType"        SET NOT NULL,
  ALTER COLUMN "isActive"        SET NOT NULL,
  ALTER COLUMN "createDate"      SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "userProfile_profileName_key"
  ON "userProfile" ("profileName");

-- ---------------------------------------------------------------------------
-- 7. Reshape the two detail tables to match the Prisma models
-- ---------------------------------------------------------------------------
ALTER TABLE "userPersonalDetails"
  ALTER COLUMN "userAdd1"       TYPE TEXT,
  ALTER COLUMN "userAdd2"       TYPE TEXT,
  ALTER COLUMN "userAdd3"       TYPE TEXT,
  ALTER COLUMN "userCity"       TYPE TEXT,
  ALTER COLUMN "userCounty"     TYPE TEXT,
  ALTER COLUMN "userZipCode"    TYPE TEXT,
  ALTER COLUMN "emailAddress"   TYPE TEXT,
  -- Phone numbers are text: an integer drops the leading 0 on UK numbers
  ALTER COLUMN "contactNumber1" TYPE TEXT USING "contactNumber1"::TEXT,
  ALTER COLUMN "contactNumber2" TYPE TEXT USING "contactNumber2"::TEXT,
  ALTER COLUMN "userDetails_Id" SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "userPersonalDetails_userDetails_Id_key"
  ON "userPersonalDetails" ("userDetails_Id");

ALTER TABLE "userPersonalDetails"
  DROP CONSTRAINT IF EXISTS "userPersonalDetails_userDetails_Id_fkey";
ALTER TABLE "userPersonalDetails"
  ADD CONSTRAINT "userPersonalDetails_userDetails_Id_fkey"
  FOREIGN KEY ("userDetails_Id") REFERENCES "userProfile"("id")
  ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "userPaymentDetails"
  ALTER COLUMN "paymentId"      TYPE TEXT,
  ALTER COLUMN "paymentAmount"  TYPE DECIMAL(10, 2),
  ALTER COLUMN "userProfile_Id" SET NOT NULL;

ALTER TABLE "userPaymentDetails"
  DROP CONSTRAINT IF EXISTS "userPaymentDetails_userProfile_Id_fkey";
ALTER TABLE "userPaymentDetails"
  ADD CONSTRAINT "userPaymentDetails_userProfile_Id_fkey"
  FOREIGN KEY ("userProfile_Id") REFERENCES "userProfile"("id")
  ON UPDATE CASCADE ON DELETE CASCADE;

-- ---------------------------------------------------------------------------
-- 8. Retire the legacy table
-- ---------------------------------------------------------------------------
ALTER TABLE "userProfile" DROP COLUMN "legacy_id";
DROP TABLE "User";
DROP TYPE IF EXISTS "Role";

COMMIT;
