-- Progress tracking for Maths practice rounds.
--
--   testTrackerMathMain : one row per test (its id identifies the test)
--   testTrackerMath     : one row per question answered in that test
--
-- The tables were created by hand before this migration ran, so this creates
-- them only if missing and then brings an existing pair up to the same shape.
-- It is idempotent and safe to re-run.
--
-- Three things are enforced beyond the original hand-written DDL:
--   * studentId gets a real foreign key to userProfile - a tracker row with no
--     student cannot be analysed, and nothing else enforces it.
--   * the key columns become NOT NULL, for the same reason.
--   * timeSpentOnQuestion is bounded to DECIMAL(7,2) seconds, so one runaway
--     client-reported value cannot skew every average.
--
-- Run once:  psql -d tasteurknowledge -f prisma/sql/008_maths_test_tracker.sql

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Create if they are not already there
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "testTrackerMathMain" (
  "id"            INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "studentId"     INTEGER,
  "testStartTime" TIMESTAMP(3),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "testTrackerMath" (
  "id"                  INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "questionId"          INTEGER,
  "studentId"           INTEGER,
  "isAnsRight"          BOOLEAN,
  "isSkipped"           BOOLEAN,
  "testId"              INTEGER,
  "timeSpentOnQuestion" DECIMAL,
  PRIMARY KEY ("id")
);

-- ---------------------------------------------------------------------------
-- 2. Refuse to tighten anything if rows are already present that would break
--    under the new constraints, rather than failing halfway.
-- ---------------------------------------------------------------------------
DO $$
DECLARE bad INTEGER;
BEGIN
  SELECT count(*) INTO bad FROM "testTrackerMathMain"
   WHERE "studentId" IS NULL OR "testStartTime" IS NULL;
  IF bad > 0 THEN
    RAISE EXCEPTION '% test row(s) have a null studentId or start time - aborting', bad;
  END IF;

  SELECT count(*) INTO bad FROM "testTrackerMath"
   WHERE "questionId" IS NULL OR "studentId" IS NULL OR "testId" IS NULL;
  IF bad > 0 THEN
    RAISE EXCEPTION '% tracker row(s) have a null key column - aborting', bad;
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 3. Column types and nullability
-- ---------------------------------------------------------------------------
ALTER TABLE "testTrackerMathMain"
  ALTER COLUMN "studentId"     SET NOT NULL,
  ALTER COLUMN "testStartTime" TYPE TIMESTAMP(3),
  ALTER COLUMN "testStartTime" SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN "testStartTime" SET NOT NULL;

ALTER TABLE "testTrackerMath"
  ALTER COLUMN "questionId"          SET NOT NULL,
  ALTER COLUMN "studentId"           SET NOT NULL,
  ALTER COLUMN "testId"              SET NOT NULL,
  ALTER COLUMN "isAnsRight"          SET DEFAULT FALSE,
  ALTER COLUMN "isSkipped"           SET DEFAULT FALSE,
  ALTER COLUMN "timeSpentOnQuestion" TYPE DECIMAL(7, 2);

UPDATE "testTrackerMath" SET "isAnsRight" = FALSE WHERE "isAnsRight" IS NULL;
UPDATE "testTrackerMath" SET "isSkipped"  = FALSE WHERE "isSkipped"  IS NULL;

ALTER TABLE "testTrackerMath"
  ALTER COLUMN "isAnsRight" SET NOT NULL,
  ALTER COLUMN "isSkipped"  SET NOT NULL;

-- ---------------------------------------------------------------------------
-- 4. Foreign keys (dropped first so re-running picks up the right actions)
-- ---------------------------------------------------------------------------
ALTER TABLE "testTrackerMathMain"
  DROP CONSTRAINT IF EXISTS "testTrackerMathMain_studentId_fkey";
ALTER TABLE "testTrackerMathMain"
  ADD CONSTRAINT "testTrackerMathMain_studentId_fkey"
  FOREIGN KEY ("studentId") REFERENCES "userProfile" ("id")
  ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "testTrackerMath"
  DROP CONSTRAINT IF EXISTS "testTrackerMath_testId_fkey";
ALTER TABLE "testTrackerMath"
  ADD CONSTRAINT "testTrackerMath_testId_fkey"
  FOREIGN KEY ("testId") REFERENCES "testTrackerMathMain" ("id")
  ON UPDATE CASCADE ON DELETE CASCADE;

-- RESTRICT: deleting a question must not erase a child's history of
-- having answered it.
ALTER TABLE "testTrackerMath"
  DROP CONSTRAINT IF EXISTS "testTrackerMath_questionId_fkey";
ALTER TABLE "testTrackerMath"
  ADD CONSTRAINT "testTrackerMath_questionId_fkey"
  FOREIGN KEY ("questionId") REFERENCES "gsMathsQuestions" ("id")
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "testTrackerMath"
  DROP CONSTRAINT IF EXISTS "testTrackerMath_studentId_fkey";
ALTER TABLE "testTrackerMath"
  ADD CONSTRAINT "testTrackerMath_studentId_fkey"
  FOREIGN KEY ("studentId") REFERENCES "userProfile" ("id")
  ON UPDATE CASCADE ON DELETE CASCADE;

-- ---------------------------------------------------------------------------
-- 5. Indexes for the two queries the parent view will actually run:
--    one student over time, and every row for one test.
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS "testTrackerMathMain_studentId_testStartTime_idx"
  ON "testTrackerMathMain" ("studentId", "testStartTime");

CREATE INDEX IF NOT EXISTS "testTrackerMath_testId_idx"
  ON "testTrackerMath" ("testId");

CREATE INDEX IF NOT EXISTS "testTrackerMath_studentId_questionId_idx"
  ON "testTrackerMath" ("studentId", "questionId");

COMMIT;
