-- Progress tracking for English comprehension rounds.
--
--   testTrackerEnglishMain : one row per test (its id identifies the test)
--   testTrackerEnglish     : one row per question answered in that test
--
-- Deliberately shaped as a mirror of the Maths pair. The common core columns
-- are named and typed identically in both, so a UNION view across subjects
-- ("which subject is weakest this week") needs no per-subject special casing,
-- and Verbal / Non-Verbal can be added later by copying this file.
--
--   common core : studentId, testStartTime, topic, subTopic, difficultyLevel,
--                 completionReason / questionId, isAnsRight, isSkipped,
--                 timeSpentOnQuestion, chosenOption, correctOption,
--                 questionOrder
--   English only: gsEngCompId, yearName, passageReadSeconds, per-question topic
--
-- Two notes on the shape:
--   * Foreign keys point child -> parent. The earlier draft had every one of
--     them inverted, which Postgres rejects outright ("there is no unique
--     constraint matching given keys for referenced table").
--   * The round-level topic / subTopic / difficultyLevel / yearName are
--     snapshots, for the same reason as migration 009: re-tagging a
--     comprehension later must not move a past result into another bucket.
--
-- subTopic is reserved rather than used: an English round spans several
-- question types, so it stays NULL until rounds can be narrowed to one type.
--
-- Run once:  psql -d tasteurknowledge -f prisma/sql/011_english_test_tracker.sql

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. The test
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "testTrackerEnglishMain" (
  "id"            INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "studentId"     INTEGER      NOT NULL,
  "testStartTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- Which comprehension was sat.
  "gsEngCompId"   INTEGER      NOT NULL,

  -- Snapshots of what the round was at the time it was sat.
  "topic"           TEXT,   -- the comprehension's title
  "subTopic"        TEXT,   -- reserved; NULL for a whole-comprehension round
  "difficultyLevel" TEXT,
  "yearName"        TEXT,

  -- English is read-then-answer, so the reading is worth measuring on its own:
  -- a child who reads for three minutes then answers quickly is doing well, a
  -- child who skims for ten seconds then labours is not, and both can land on
  -- the same score. Counted from the story appearing to the first interaction
  -- with the question pane; per-question timing starts at that same instant,
  -- so nothing is counted twice.
  "passageReadSeconds" DECIMAL(7, 2),

  -- 'submitted' | 'timed_out' | 'abandoned'. English has no clock today, but
  -- the column is here so the union with Maths stays uniform.
  "completionReason" TEXT,

  -- Set only by the backfill in 012, so historical attempts can be carried in
  -- without ever being imported twice. NULL for everything recorded live.
  "legacyAttemptId" TEXT,

  PRIMARY KEY ("id")
);

-- ---------------------------------------------------------------------------
-- 2. One row per question answered
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "testTrackerEnglish" (
  "id"         INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "testId"     INTEGER NOT NULL,
  "questionId" INTEGER NOT NULL,
  "studentId"  INTEGER NOT NULL,
  "isAnsRight" BOOLEAN NOT NULL DEFAULT FALSE,
  "isSkipped"  BOOLEAN NOT NULL DEFAULT FALSE,

  -- Seconds, to 2dp, clamped server-side before it is stored.
  "timeSpentOnQuestion" DECIMAL(7, 2),

  -- Which answer was given and which was right. Comprehension distractors are
  -- written around specific misreadings, so the wrong answer a child reaches
  -- for repeatedly says more than the fact that they were wrong.
  "chosenOption"  VARCHAR(1),
  "correctOption" VARCHAR(1),

  -- Position in the round as it was presented. Questions about a passage run
  -- in text order, so a fall-off in the later ones separates "did not finish
  -- reading" from "did not understand".
  "questionOrder" SMALLINT,

  -- Snapshot of the question's type tag (inference, vocabulary, retrieval...).
  "topic" TEXT,

  PRIMARY KEY ("id")
);

-- ---------------------------------------------------------------------------
-- 3. Foreign keys, child -> parent (dropped first so re-running is safe)
-- ---------------------------------------------------------------------------
ALTER TABLE "testTrackerEnglishMain"
  DROP CONSTRAINT IF EXISTS "testTrackerEnglishMain_studentId_fkey";
ALTER TABLE "testTrackerEnglishMain"
  ADD CONSTRAINT "testTrackerEnglishMain_studentId_fkey"
  FOREIGN KEY ("studentId") REFERENCES "userProfile" ("id")
  ON UPDATE CASCADE ON DELETE CASCADE;

-- RESTRICT: retiring a comprehension must not erase the history of it.
ALTER TABLE "testTrackerEnglishMain"
  DROP CONSTRAINT IF EXISTS "testTrackerEnglishMain_gsEngCompId_fkey";
ALTER TABLE "testTrackerEnglishMain"
  ADD CONSTRAINT "testTrackerEnglishMain_gsEngCompId_fkey"
  FOREIGN KEY ("gsEngCompId") REFERENCES "gsEnglishComp" ("id")
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "testTrackerEnglish"
  DROP CONSTRAINT IF EXISTS "testTrackerEnglish_testId_fkey";
ALTER TABLE "testTrackerEnglish"
  ADD CONSTRAINT "testTrackerEnglish_testId_fkey"
  FOREIGN KEY ("testId") REFERENCES "testTrackerEnglishMain" ("id")
  ON UPDATE CASCADE ON DELETE CASCADE;

-- RESTRICT: deleting a question must not erase a child's history of it.
ALTER TABLE "testTrackerEnglish"
  DROP CONSTRAINT IF EXISTS "testTrackerEnglish_questionId_fkey";
ALTER TABLE "testTrackerEnglish"
  ADD CONSTRAINT "testTrackerEnglish_questionId_fkey"
  FOREIGN KEY ("questionId") REFERENCES "gsEnglishQuestions" ("id")
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "testTrackerEnglish"
  DROP CONSTRAINT IF EXISTS "testTrackerEnglish_studentId_fkey";
ALTER TABLE "testTrackerEnglish"
  ADD CONSTRAINT "testTrackerEnglish_studentId_fkey"
  FOREIGN KEY ("studentId") REFERENCES "userProfile" ("id")
  ON UPDATE CASCADE ON DELETE CASCADE;

-- ---------------------------------------------------------------------------
-- 4. Indexes for the queries the parent view will actually run
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS "testTrackerEnglishMain_studentId_testStartTime_idx"
  ON "testTrackerEnglishMain" ("studentId", "testStartTime");

-- Serves "last 3 results for this comprehension" on the English dashboard.
CREATE INDEX IF NOT EXISTS "testTrackerEnglishMain_student_round_idx"
  ON "testTrackerEnglishMain"
     ("studentId", "gsEngCompId", "difficultyLevel", "testStartTime");

-- Makes the backfill idempotent: a legacy attempt can only land once.
-- Postgres treats NULLs as distinct, so every live round still inserts freely.
CREATE UNIQUE INDEX IF NOT EXISTS "testTrackerEnglishMain_legacyAttemptId_key"
  ON "testTrackerEnglishMain" ("legacyAttemptId");

CREATE INDEX IF NOT EXISTS "testTrackerEnglish_testId_idx"
  ON "testTrackerEnglish" ("testId");

CREATE INDEX IF NOT EXISTS "testTrackerEnglish_studentId_questionId_idx"
  ON "testTrackerEnglish" ("studentId", "questionId");

COMMIT;
