-- Password reset links.
--
-- A password cannot be sent to anyone: profilePassword holds a bcrypt hash and
-- there is no way back from it to the original text. That is deliberate - a
-- database leak must not hand over the account. So "forgot password" issues a
-- short-lived link instead, and the person chooses a new password themselves.
--
-- What is stored here is the SHA-256 of the token, never the token itself, for
-- the same reason passwords are hashed: anyone who reads this table must not
-- be able to use what they find. The raw token exists only in the emailed URL.
--
-- SHA-256 rather than bcrypt because the token is 32 random bytes, not a
-- human-chosen secret - there is nothing to brute force, and bcrypt's slowness
-- would only punish the lookup.
--
-- Run once:  psql -d tasteurknowledge -f prisma/sql/016_password_reset_tokens.sql

BEGIN;

CREATE TABLE IF NOT EXISTS "passwordResetToken" (
  "id"        INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "userId"    INTEGER      NOT NULL,
  /** SHA-256 hex of the token that went out in the link. */
  "tokenHash" TEXT         NOT NULL,
  "expiresAt" TIMESTAMPTZ(3) NOT NULL,
  /** Set the moment the link is spent, so a link works exactly once. */
  "usedAt"    TIMESTAMPTZ(3),
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

ALTER TABLE "passwordResetToken"
  DROP CONSTRAINT IF EXISTS "passwordResetToken_userId_fkey";
ALTER TABLE "passwordResetToken"
  ADD CONSTRAINT "passwordResetToken_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "userProfile" ("id")
  ON UPDATE CASCADE ON DELETE CASCADE;

-- The lookup the reset page runs, and the guarantee that one token is one row.
CREATE UNIQUE INDEX IF NOT EXISTS "passwordResetToken_tokenHash_key"
  ON "passwordResetToken" ("tokenHash");

-- "every outstanding request for this account", used to retire older links
-- when a new one is asked for.
CREATE INDEX IF NOT EXISTS "passwordResetToken_userId_idx"
  ON "passwordResetToken" ("userId");

COMMIT;
