-- Non-Verbal Reasoning question bank.
--
-- Figures are stored as SVG markup and rendered inline, which is the one place
-- in this app where stored content becomes live markup in a child's browser.
-- Three things keep that safe, and all three matter:
--
--   1. assetOrigin records where a figure came from; only original geometry
--      goes in, which also keeps the bank clear of third-party 11+ material.
--   2. nvr_no_markup below refuses anything that can execute, at the database,
--      so a bad row cannot be inserted by any route - app, psql or otherwise.
--   3. The renderer strips what survives. A regex blacklist is leaky by
--      nature; it is a second line, never the only one.
--
-- Differences from the drafted DDL, and why:
--
--   * id is INTEGER IDENTITY, not bigserial. Every tracker row references a
--     question with "questionId" INTEGER, and PostgreSQL will not create a
--     foreign key from an integer column to a bigint one. Starting bigint
--     would mean altering a populated primary key the day NVR results reach
--     the parent report.
--   * yearName is nullable. Year stopped gating content in this app; it is
--     metadata now, and every other bank treats it that way.
--   * stemFormat and optionFormat are constrained. Both drive rendering, so
--     'SVG' instead of 'svg' would silently render nothing.
--   * Indexes exist. The picker filters on difficulty and topic on every page
--     load, exactly as the Maths picker does.
--
-- Run once:  psql -d tasteurknowledge -f prisma/sql/018_nvr_questions.sql

BEGIN;

CREATE TABLE IF NOT EXISTS public."gsNvrQuestions" (
  "id"              INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "yearName"        TEXT,
  "subjectName"     TEXT NOT NULL DEFAULT 'Non-Verbal Reasoning',
  "topic"           TEXT NOT NULL,
  "subTopic"        TEXT NOT NULL,
  /* 'Odd one out' | 'Sequence' | 'Analogy' | 'Matrix' | 'Mirror image' ...
     Same column name as gsEnglishQuestions, so the parent report groups
     weaknesses by skill here too. */
  "typeOfQuestion"  TEXT NOT NULL,
  "difficultyLevel" TEXT NOT NULL,
  "quest"           TEXT NOT NULL,

  "stemFormat"      TEXT NOT NULL DEFAULT 'svg',
  "stemFigure"      TEXT,
  "optionFormat"    TEXT NOT NULL DEFAULT 'svg',
  "optionA"         TEXT NOT NULL,
  "optionB"         TEXT NOT NULL,
  "optionC"         TEXT NOT NULL,
  "optionD"         TEXT NOT NULL,
  /* Four options is kinder at this age; E stays optional. */
  "optionE"         TEXT,
  "ansChoice"       CHAR(1) NOT NULL,
  /* The "why", for a parent or tutor going through a wrong answer. */
  "ansExplain"      TEXT,

  "assetOrigin"     TEXT NOT NULL DEFAULT 'original-generated',
  "createdAt"       TIMESTAMPTZ(3) NOT NULL DEFAULT now(),

  PRIMARY KEY ("id"),

  CONSTRAINT nvr_ans_valid
    CHECK ("ansChoice" IN ('A','B','C','D','E')),
  CONSTRAINT nvr_ans_exists
    CHECK ("ansChoice" <> 'E' OR "optionE" IS NOT NULL),
  CONSTRAINT nvr_stem_format
    CHECK ("stemFormat" IN ('svg','url','none')),
  CONSTRAINT nvr_option_format
    CHECK ("optionFormat" IN ('svg','url','none'))
);

-- ---------------------------------------------------------------------------
-- Nothing executable in a figure.
--
-- \m anchors to the start of a word, so "on" must begin an attribute name:
-- that catches onclick, onerror, onmouseover and the rest without tripping on
-- "polygon points=", which merely ends in those two letters.
-- ---------------------------------------------------------------------------
ALTER TABLE public."gsNvrQuestions"
  DROP CONSTRAINT IF EXISTS nvr_no_script;
ALTER TABLE public."gsNvrQuestions"
  DROP CONSTRAINT IF EXISTS nvr_no_markup;
ALTER TABLE public."gsNvrQuestions"
  ADD CONSTRAINT nvr_no_markup CHECK (
    coalesce("stemFigure",'') || "optionA" || "optionB" || "optionC"
      || "optionD" || coalesce("optionE",'')
    !~* '<script|<foreignObject|<use\M|<animate|<set\M|javascript:|\mon[a-z]+\s*='
  );

-- ---------------------------------------------------------------------------
-- The queries the picker runs
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS "gsNvrQuestions_topic_level_idx"
  ON public."gsNvrQuestions" ("topic", "difficultyLevel");

CREATE INDEX IF NOT EXISTS "gsNvrQuestions_subTopic_level_idx"
  ON public."gsNvrQuestions" ("subTopic", "difficultyLevel");

-- Serves the parent report's "weakest question type".
CREATE INDEX IF NOT EXISTS "gsNvrQuestions_typeOfQuestion_idx"
  ON public."gsNvrQuestions" ("typeOfQuestion");

COMMIT;
