-- Progress tracking for Non-Verbal Reasoning rounds.
--
-- Third copy of the same pair, on purpose. The shared columns are named and
-- typed identically to the Maths and English trackers, so one UNION answers
-- "which subject is weakest" without per-subject special casing. Verbal will
-- be a fourth copy of this file.
--
--   common core : studentId, testStartTime, topic, subTopic, difficultyLevel,
--                 completionReason / questionId, isAnsRight, isSkipped,
--                 timeSpentOnQuestion, chosenOption, correctOption,
--                 questionOrder, topic
--
-- Foreign keys point child -> parent. gsNvrQuestions.id is INTEGER precisely
-- so questionId below can reference it.
--
-- Run once:  psql -d tasteurknowledge -f prisma/sql/019_nvr_test_tracker.sql

BEGIN;

CREATE TABLE IF NOT EXISTS "testTrackerNvrMain" (
  "id"            INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "studentId"     INTEGER      NOT NULL,
  "testStartTime" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- Snapshots of what the round was, so re-tagging a question later cannot
  -- move a past result into a different bucket.
  "topic"           TEXT,
  -- Null marks a whole-topic test spanning several subtopics.
  "subTopic"        TEXT,
  "difficultyLevel" TEXT,
  "completionReason" TEXT,

  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "testTrackerNvr" (
  "id"         INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "testId"     INTEGER NOT NULL,
  "questionId" INTEGER NOT NULL,
  "studentId"  INTEGER NOT NULL,
  "isAnsRight" BOOLEAN NOT NULL DEFAULT FALSE,
  "isSkipped"  BOOLEAN NOT NULL DEFAULT FALSE,
  "timeSpentOnQuestion" DECIMAL(7, 2),
  "chosenOption"  VARCHAR(1),
  "correctOption" VARCHAR(1),
  "questionOrder" SMALLINT,
  -- The question type snapshot: "Mirror image", "Quarter turn" and so on.
  -- This is what the parent report groups weaknesses by.
  "topic" TEXT,
  PRIMARY KEY ("id")
);

ALTER TABLE "testTrackerNvrMain"
  DROP CONSTRAINT IF EXISTS "testTrackerNvrMain_studentId_fkey";
ALTER TABLE "testTrackerNvrMain"
  ADD CONSTRAINT "testTrackerNvrMain_studentId_fkey"
  FOREIGN KEY ("studentId") REFERENCES "userProfile" ("id")
  ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "testTrackerNvr"
  DROP CONSTRAINT IF EXISTS "testTrackerNvr_testId_fkey";
ALTER TABLE "testTrackerNvr"
  ADD CONSTRAINT "testTrackerNvr_testId_fkey"
  FOREIGN KEY ("testId") REFERENCES "testTrackerNvrMain" ("id")
  ON UPDATE CASCADE ON DELETE CASCADE;

-- RESTRICT: deleting a question must not erase a child's history of it.
ALTER TABLE "testTrackerNvr"
  DROP CONSTRAINT IF EXISTS "testTrackerNvr_questionId_fkey";
ALTER TABLE "testTrackerNvr"
  ADD CONSTRAINT "testTrackerNvr_questionId_fkey"
  FOREIGN KEY ("questionId") REFERENCES "gsNvrQuestions" ("id")
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "testTrackerNvr"
  DROP CONSTRAINT IF EXISTS "testTrackerNvr_studentId_fkey";
ALTER TABLE "testTrackerNvr"
  ADD CONSTRAINT "testTrackerNvr_studentId_fkey"
  FOREIGN KEY ("studentId") REFERENCES "userProfile" ("id")
  ON UPDATE CASCADE ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS "testTrackerNvrMain_studentId_testStartTime_idx"
  ON "testTrackerNvrMain" ("studentId", "testStartTime");

CREATE INDEX IF NOT EXISTS "testTrackerNvrMain_student_round_idx"
  ON "testTrackerNvrMain"
     ("studentId", "topic", "subTopic", "difficultyLevel", "testStartTime");

CREATE INDEX IF NOT EXISTS "testTrackerNvr_testId_idx"
  ON "testTrackerNvr" ("testId");

CREATE INDEX IF NOT EXISTS "testTrackerNvr_studentId_questionId_idx"
  ON "testTrackerNvr" ("studentId", "questionId");

COMMIT;
