-- One row per login, closed on logout: an audit trail of who was on and when.
--
--   loginAt   set when the login succeeds
--   logoutAt  set when the user explicitly logs out; NULL while still on, or
--             if the session was abandoned (tab closed, cookie expired) - the
--             app only sees an explicit logout, so those stay open.
--   endReason 'logout' for an explicit sign-out; NULL otherwise.
--
-- Matching a logout to its login is "the user's most recent still-open row",
-- which is exact for the common one-device case. With two devices at once,
-- logging out of one closes the newer open row; good enough for an audit log
-- and avoids putting a session id in the cookie.
--
-- Run once:  psql -d tasteurknowledge -f prisma/sql/020_login_sessions.sql

BEGIN;

CREATE TABLE IF NOT EXISTS "userLoginSession" (
  "id"        INTEGER        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "userId"    INTEGER        NOT NULL,
  "loginAt"   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  "logoutAt"  TIMESTAMPTZ(3),
  "endReason" TEXT,
  PRIMARY KEY ("id")
);

ALTER TABLE "userLoginSession"
  DROP CONSTRAINT IF EXISTS "userLoginSession_userId_fkey";
ALTER TABLE "userLoginSession"
  ADD CONSTRAINT "userLoginSession_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "userProfile" ("id")
  ON UPDATE CASCADE ON DELETE CASCADE;

-- Serves both the per-user history and the "find the open session to close on
-- logout" lookup (userId prefix, then the few rows for that user). Plain and
-- ascending so it is exactly what the Prisma @@index declares - a DESC or
-- partial index cannot be expressed in the schema and would read as drift.
CREATE INDEX IF NOT EXISTS "userLoginSession_userId_loginAt_idx"
  ON "userLoginSession" ("userId", "loginAt");

COMMIT;
